# Generated by Django 3.2 on 2022-08-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220803_2011'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTimeItem',
            new_name='OrderLineItem',
        ),
    ]
